# Generated by Django 4.1.9 on 2023-05-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail-Adresse')),
                ('msg_planning', models.TextField(blank=True, verbose_name='Planung')),
                ('msg_volunteer_event', models.TextField(blank=True, verbose_name='Helfer-Treffen')),
                ('msg_construction', models.TextField(blank=True, verbose_name='Aufbau')),
                ('msg_shift', models.TextField(blank=True, verbose_name='Schicht')),
                ('msg_dismantling', models.TextField(blank=True, verbose_name='Abbau')),
                ('msg_ambience', models.TextField(blank=True, verbose_name='Atmosphäre')),
                ('msg_music', models.TextField(blank=True, verbose_name='Musik')),
                ('msg_chief_organiser', models.TextField(blank=True, verbose_name='Haupt-Organisatoren')),
                ('msg_catering', models.TextField(blank=True, verbose_name='Verpflegung')),
                ('msg_prices', models.TextField(blank=True, verbose_name='Preise')),
                ('msg_sales', models.TextField(blank=True, verbose_name='Kartenverkauf')),
                ('msg_misc', models.TextField(blank=True, verbose_name='Sonstiges')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Bewertung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bewertung',
                'verbose_name_plural': 'Bewertungen',
                'ordering': ['created_at'],
            },
        ),
    ]
