# Generated by Django 4.1.7 on 2023-02-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail-Adresse')),
                ('phone', models.CharField(max_length=20, verbose_name='Mobilnummer')),
                ('faculty', models.CharField(choices=[('MEE', 'Maschinenbau'), ('PSE', 'Verfahrens- und Systemtechnik'), ('EIT', 'Elektro- und Informationstechnik'), ('COS', 'Informatik'), ('MAT', 'Mathematik'), ('NAS', 'Naturwissenschaften'), ('MED', 'Medizin'), ('SSE', 'Humanwissenschaften'), ('ECM', 'Wirtschaftswissenschaften')], max_length=3, verbose_name='Fakultät')),
                ('experience', models.TextField(blank=True, verbose_name='Erfahrung')),
                ('strength', models.PositiveSmallIntegerField(verbose_name='Stärke')),
            ],
            options={
                'verbose_name': 'Helfer',
                'verbose_name_plural': 'Helfer',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
