# Generated by Django 4.1.7 on 2023-02-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_worker_available_since_worker_available_until_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('can_contact', 'Can contact workers per email')], 'verbose_name': 'Helfer', 'verbose_name_plural': 'Helfer'},
        ),
    ]
